export const VIEWTEMPLATE_DATA_REQUEST = "VIEWTEMPLATE_DATA_REQUEST";
export const VIEWTEMPLATE_DATA_SUCCESS = "VIEWTEMPLATE_DATA_SUCCESS";
export const VIEWTEMPLATE_DATA_ERROR = "VIEWTEMPLATE_DATA_ERROR";

export const VIEWTEMPARCHIVE_DATA_REQUEST = "VIEWTEMPARCHIVE_DATA_REQUEST";
export const VIEWTEMPARCHIVE_DATA_SUCCESS = "VIEWTEMPARCHIVE_DATA_SUCCESS";
export const VIEWTEMPARCHIVE_DATA_ERROR = "VIEWTEMPARCHIVE_DATA_ERROR";

export const VIEWSUBJECT_DATA_REQUEST = "VIEWSUBJECT_DATA_REQUEST";
export const VIEWSUBJECT_DATA_SUCCESS = "VIEWSUBJECT_DATA_SUCCESS";
export const VIEWSUBJECT_DATA_ERROR = "VIEWSUBJECT_DATA_ERROR";

export const CREATETEMPLATE_DATA_REQUEST = "CREATETEMPLATE_DATA_REQUEST";
export const CREATETEMPLATE_DATA_SUCCESS = "CREATETEMPLATE_DATA_SUCCESS";
export const CREATETEMPLATE_DATA_ERROR = "CREATETEMPLATE_DATA_ERROR";
